import Image from "next/image";
import Link from "next/link";
import { FiArrowRight, FiArrowUpRight, FiHeart, FiMapPin, FiShield, FiShoppingBag, FiStar, FiTruck } from "react-icons/fi";

const categories = [
  { name: "Accessories", count: "48 products", image: "/ecommerce/assoceries.png", color: "bg-[#f4dfe4]" },
  { name: "Home & living", count: "36 products", image: "/ecommerce/packingtips2.jpg", color: "bg-[#f6e8c8]" },
  { name: "Style & wear", count: "64 products", image: "/ecommerce/chillshop.png", color: "bg-[#dce9df]" },
  { name: "Gifts from Nepal", count: "28 products", image: "/ecommerce/e-commerce - Copy.png", color: "bg-[#e5def0]" },
];

const products = [
  { name: "Everyday accessories", maker: "Made by Maya", price: "रू 1,850", rating: "4.9", image: "/ecommerce/assoceries.png", color: "bg-[#f5dfd5]" },
  { name: "A thoughtful travel kit", maker: "Koshi Studio", price: "रू 950", rating: "4.8", image: "/ecommerce/packingtips2.jpg", color: "bg-[#efe4c7]" },
  { name: "A new season of style", maker: "Patan Looms", price: "रू 3,200", rating: "5.0", image: "/ecommerce/chillshop.png", color: "bg-[#dce5df]" },
];

export default function Home() {
  return <main className="overflow-hidden">
    <section className="relative bg-[#f8e8ec]">
      <div className="absolute -right-32 -top-44 h-[32rem] w-[32rem] rounded-full bg-[#e7c2cc]/60" />
      <div className="absolute -bottom-36 left-[42%] h-72 w-72 rounded-full border-[30px] border-white/40" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-10 px-5 py-16 sm:px-8 sm:py-20 lg:grid-cols-[1.02fr_0.98fr] lg:px-12 lg:py-24">
        <div className="max-w-2xl">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#e4b5c2] bg-white/60 px-4 py-2 text-xs font-bold uppercase tracking-[0.2em] text-[#9c3155]"><span className="h-2 w-2 rounded-full bg-[#b91c4a]" />Rooted in Nepal</div>
          <h1 className="max-w-2xl text-5xl font-black leading-[1.03] tracking-tight text-[#251b2b] sm:text-6xl lg:text-7xl">Small joys, <span className="text-[#b91c4a]">beautifully</span> made.</h1>
          <p className="mt-7 max-w-lg text-base leading-7 text-[#756875] sm:text-lg">Discover thoughtful products made by Nepal&apos;s finest makers. Every purchase carries a story, a skill, and a little piece of home.</p>
          <div className="mt-9 flex flex-wrap items-center gap-4"><Link href="/products" className="inline-flex items-center gap-3 rounded-xl bg-[#b91c4a] px-6 py-4 text-sm font-bold text-white shadow-xl shadow-[#b91c4a]/20 transition hover:-translate-y-0.5 hover:bg-[#8f153a]">Explore the collection <FiArrowRight size={18} /></Link><Link href="/about-us" className="inline-flex items-center gap-2 px-3 py-3 text-sm font-bold text-[#7f153d] hover:text-[#b91c4a]">Our story <FiArrowUpRight size={17} /></Link></div>
          <div className="mt-12 flex flex-wrap gap-7 text-sm text-[#756875]"><span className="flex items-center gap-2"><FiTruck className="text-[#b91c4a]" />Nationwide delivery</span><span className="flex items-center gap-2"><FiShield className="text-[#b91c4a]" />Made with care</span></div>
        </div>
        <div className="relative mx-auto w-full max-w-lg lg:ml-auto">
          <div className="relative aspect-[0.88] overflow-hidden rounded-[2rem] bg-[#7f153d] shadow-2xl shadow-[#7f153d]/20"><Image src="/ecommerce/e-commerce - Copy.png" alt="A beautiful local collection" fill className="object-cover" priority /><div className="absolute inset-0 bg-gradient-to-t from-[#7f153d] via-[#7f153d]/10 to-black/5" /><div className="relative flex h-full flex-col justify-between p-6 sm:p-8"><div className="flex items-center justify-between"><span className="rounded-full border border-white/30 bg-[#7f153d]/45 px-4 py-2 text-[11px] font-bold uppercase tracking-[0.18em] text-white backdrop-blur-sm">Curated locally</span><button aria-label="Add collection to wishlist" className="flex h-11 w-11 items-center justify-center rounded-full bg-white text-[#b91c4a] shadow-lg transition hover:scale-105"><FiHeart size={19} /></button></div><div className="flex items-end justify-between gap-4"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[0.18em] text-white/70">Featured collection</p><p className="text-2xl font-black leading-tight text-white sm:text-3xl">Style made personal</p></div><Image src="/logo.png" alt="Nepali Store" width={68} height={68} className="h-14 w-14 shrink-0 rounded-full bg-white/90 object-contain p-1.5" /></div></div></div>
        </div>
      </div>
    </section>

    <section className="border-b border-[#f0e5e3] bg-white"><div className="mx-auto grid max-w-7xl gap-5 px-5 py-7 sm:grid-cols-3 sm:px-8 lg:grid-cols-3 lg:px-12"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#f7e8ed] text-[#b91c4a]"><FiMapPin /></span><div><p className="text-sm font-bold">From Nepal, with love</p><p className="mt-1 text-xs text-[#9a8e98]">Products with a place and purpose</p></div></div><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#f7e8ed] text-[#b91c4a]"><FiStar /></span><div><p className="text-sm font-bold">Makers you can trust</p><p className="mt-1 text-xs text-[#9a8e98]">Thoughtfully selected for you</p></div></div><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#f7e8ed] text-[#b91c4a]"><FiTruck /></span><div><p className="text-sm font-bold">Easy delivery</p><p className="mt-1 text-xs text-[#9a8e98]">Little joys, sent to your door</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mb-9 flex items-end justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.25em] text-[#b91c4a]">Find your feeling</p><h2 className="text-3xl font-black tracking-tight sm:text-4xl">Shop by collection</h2></div><Link href="/products" className="hidden items-center gap-2 text-sm font-bold text-[#b91c4a] sm:flex">View all <FiArrowRight /></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category) => <Link href="/products" key={category.name} className={`group relative overflow-hidden rounded-2xl ${category.color} p-3 transition hover:-translate-y-1 hover:shadow-xl`}><div className="relative mb-5 h-36 overflow-hidden rounded-xl"><Image src={category.image} alt={category.name} fill className="object-cover transition duration-500 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-black/30 to-transparent" /></div><div className="px-3 pb-3"><p className="text-lg font-black">{category.name}</p><div className="mt-2 flex items-center justify-between text-xs text-[#756875]"><span>{category.count}</span><FiArrowUpRight className="text-[#b91c4a]" size={18} /></div></div></Link>)}</div></section>

    <section className="bg-[#fffaf5]"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mb-9 flex items-end justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.25em] text-[#b91c4a]">Made for keeping</p><h2 className="text-3xl font-black tracking-tight sm:text-4xl">A few good things</h2></div><Link href="/products" className="hidden items-center gap-2 text-sm font-bold text-[#b91c4a] sm:flex">Shop all products <FiArrowRight /></Link></div><div className="grid gap-5 md:grid-cols-3">{products.map((product) => <article key={product.name} className="group rounded-2xl border border-[#eadfe2] bg-white p-3 transition hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(83,27,47,0.1)]"><div className={`relative aspect-[1.15] overflow-hidden rounded-xl ${product.color}`}><Image src={product.image} alt={product.name} fill className="object-cover transition duration-500 group-hover:scale-105" /><button aria-label={`Add ${product.name} to wishlist`} className="absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-full bg-white/80 text-[#756875] hover:text-[#b91c4a]"><FiHeart size={17} /></button></div><div className="px-2 pb-2 pt-5"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-semibold text-[#a799a0]">{product.maker}</span><span className="flex items-center gap-1 text-xs font-bold text-[#9d7620]"><FiStar size={13} fill="currentColor" />{product.rating}</span></div><h3 className="font-black">{product.name}</h3><div className="mt-4 flex items-center justify-between"><p className="font-bold text-[#b91c4a]">{product.price}</p><Link href="/products" className="flex h-9 w-9 items-center justify-center rounded-full bg-[#f7e8ed] text-[#b91c4a] transition hover:bg-[#b91c4a] hover:text-white" aria-label={`View ${product.name}`}><FiShoppingBag size={16} /></Link></div></div></article>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="grid overflow-hidden rounded-[2rem] bg-[#7f153d] lg:grid-cols-[0.9fr_1.1fr]"><div className="relative min-h-72 overflow-hidden p-8 sm:p-12"><div className="absolute -left-20 -top-20 h-64 w-64 rounded-full border-[26px] border-[#d9a441]/30" /><div className="absolute -bottom-28 right-0 h-72 w-72 rounded-full bg-[#b91c4a]" /><div className="relative flex h-full items-center justify-center"><span className="text-[9rem] drop-shadow-2xl">🧵</span></div></div><div className="flex flex-col justify-center p-8 text-white sm:p-12 lg:p-16"><p className="mb-3 text-xs font-bold uppercase tracking-[0.25em] text-[#f5d58a]">More than a marketplace</p><h2 className="max-w-lg text-3xl font-black leading-tight sm:text-4xl">Every purchase helps a local story continue.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-white/70">We bring together independent makers, family workshops, and creative minds from across Nepal. Find something meaningful, and help keep their craft alive.</p><Link href="/about-us" className="mt-8 inline-flex w-fit items-center gap-3 rounded-xl bg-white px-5 py-3.5 text-sm font-bold text-[#7f153d] transition hover:bg-[#f5d58a]">Meet the makers <FiArrowRight /></Link></div></div></section>

    <section className="bg-[#f6e8c8]"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 px-5 py-12 sm:px-8 md:flex-row md:items-center lg:px-12"><div><p className="text-2xl font-black tracking-tight text-[#251b2b]">Good things are waiting.</p><p className="mt-2 text-sm text-[#756875]">Take a slower look around. You might find your new favourite.</p></div><Link href="/products" className="inline-flex items-center gap-3 rounded-xl bg-[#251b2b] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#b91c4a]">Start exploring <FiArrowRight /></Link></div></section>
  </main>;
}
